services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
